[package]
name = "slab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#doubly-linked-list = {git = "https://github.com/os-module/doubly-linked-list"}
spin = "0.9.2"
log = "0.4.14"
bitflags = "1.3.2"
doubly-linked-list = {path = "../double-link-list"}